# Configuration for welcome - https://github.com/behaviorbot/welcome

# Configuration for new-issue-welcome - https://github.com/behaviorbot/new-issue-welcome

# Comment to be posted to on first time issues
newIssueWelcomeComment: |
  Thanks for opening your first issue! ğŸ‘ğŸ‰ğŸ˜„âš¡ï¸
  Do join our [Gitter channel](https://gitter.im/aboutcode-org/gsod-season-of-docs) for more discussions. 
# Configuration for new-pr-welcome - https://github.com/behaviorbot/new-pr-welcome

# Comment to be posted to on PRs from first time contributors in your repository
newPRWelcomeComment: |
 Thanks for opening this pull request! ğŸ‘ğŸ‰ğŸ˜„âš¡ï¸
 Also please refer [Contributing related documentation](https://aboutcode.readthedocs.io/en/latest/doc_maintenance.html) for more help! ğŸ’¿
 
# Configuration for first-pr-merge - https://github.com/behaviorbot/first-pr-merge

# Comment to be posted to on pull requests merged by a first time user
firstPRMergeComment: |
 Congrats on merging your first pull request! ğŸ‘ğŸ‰ğŸ˜„âš¡ï¸
 Now that you've completed this, you can help on more [Issues](https://github.com/nexB/aboutcode/issues)

# It is recommend to include as many gifs and emojis as possible
